# Generated by Django 2.1.1 on 2020-05-27 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=64, verbose_name='File Name')),
                ('size', models.CharField(max_length=64, verbose_name='Size')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='Sent time')),
                ('field', models.CharField(max_length=64, verbose_name='Field')),
            ],
            options={
                'db_table': 'Files',
                'ordering': ['file_name'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(default='1', max_length=64, verbose_name='Group Id')),
            ],
            options={
                'db_table': 'Group',
                'ordering': ['group_id'],
            },
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=64, unique=True, verbose_name='Lesson Name')),
                ('class_id', models.CharField(default=67, max_length=64, verbose_name='Lesson id')),
                ('teachers', models.CharField(blank=True, max_length=64, unique=True, verbose_name='Teacher Name')),
                ('time_span', models.CharField(max_length=128, verbose_name='Time Span')),
            ],
            options={
                'db_table': 'Lessons',
                'ordering': ['lesson_name'],
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_title', models.CharField(max_length=64, verbose_name='Notice Title')),
                ('teachers', models.CharField(max_length=64, verbose_name='Instructor')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='Sent time')),
                ('msgid', models.CharField(default=74, max_length=64, verbose_name='Lesson Id')),
                ('lessons', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Lessons')),
            ],
            options={
                'db_table': 'Notice',
                'ordering': ['notice_title'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=64, verbose_name='Teachername')),
                ('teacher_id', models.CharField(max_length=64, verbose_name='Teachername')),
            ],
            options={
                'db_table': 'Teacher',
                'ordering': ['teacher_name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=64, verbose_name='Password')),
                ('email', models.CharField(blank=True, max_length=64, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=64, verbose_name='Telephone')),
                ('user_status', models.CharField(choices=[('Te', 'Teacher'), ('S', 'Student')], default='S', max_length=1)),
                ('employeeID', models.CharField(blank=True, max_length=64, verbose_name='StudentID')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='Last modified')),
                ('major', models.CharField(blank=True, max_length=128, verbose_name='Major')),
                ('sex', models.CharField(blank=True, max_length=128, verbose_name='Sex')),
                ('real_name', models.CharField(blank=True, max_length=64, verbose_name='Real name')),
                ('admissions', models.CharField(blank=True, max_length=64, verbose_name='Admissions')),
            ],
            options={
                'verbose_name': 'User Profile',
            },
        ),
        migrations.AddField(
            model_name='lessons',
            name='students',
            field=models.ManyToManyField(related_name='Students', to='backend.UserProfile'),
        ),
        migrations.AddField(
            model_name='group',
            name='lessons',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Lessons'),
        ),
        migrations.AddField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(related_name='Groups', to='backend.UserProfile'),
        ),
        migrations.AddField(
            model_name='files',
            name='lessons',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Lessons'),
        ),
    ]
